checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs
