project_id: '624298'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:

  - source: /readme/**/*
    translation: /readme/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore: 
      - /readme/_i18n
      - /readme/i18n
      - /readme/about/changelog
      - /readme/about/stats.md
      - /readme/api
      - /readme/dev
      - /readme/news
      - /readme/cla.md
      - /readme/connection_check.md
      - /readme/privacy.md
      - /**/*.yml
      - /**/*.json
      - /**/*.png
      - /**/*.jpg
    