blank_issues_enabled: false
# contact_links:
#     - name: "\U0001F914 Feature requests and support"
#       url: https://discourse.joplinapp.org/
#       about: I have a question or feature request …
