# The goal of this action is to compile the Android debug build. That should
# tell us automatically if something got broken when a dependency was changed.

name: react-native-android-build-apk
on: [push, pull_request]

jobs:
  pre_job:
    if: github.repository == 'XilinJia/xilinota'
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

  BuildAndroidDebug:
    needs: pre_job
    if: github.repository == 'XilinJia/xilinota' && (needs.pre_job.outputs.should_skip != 'true' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y libsecret-1-dev
          
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'yarn'

      - name: Install Yarn
        run: |
          corepack enable

      - name: Install
        run:  yarn install

      - name: Build Android Debug
        run: |
          cd packages/app-mobile/android && ./gradlew assembleDebug
          
